version: 2.1

jobs:
    build-and-test:
        docker:
            - image: circleci/node:10-browsers
        steps:
            - checkout
            - run:
                name: Show current branch
                command: echo ${CIRCLE_BRANCH}
            - run:
                name: Versions
                command: |
                    echo "Node version: $(node --version)"
                    echo "NPM version: $(npm --version)"
            - restore_cache:
                keys:
                    - v1-dependencies-{{ checksum "package-lock.json" }}
                    - v1-dependencies-
            - run:
                name: Install local dependencies
                command: npm install
            - save_cache:
                key: v1-dependencies-{{ checksum "package-lock.json" }}
                paths:
                    - node_modules
            - run:
                name: Linting
                command: npm run lint
            - run:
                name: Unit test
                command: npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
            # - run:
            #     name: End to End Test
            #     command: npm run e2e -- --protractor-config=e2e/protractor-ci.conf.js

            - run:
                name: Build
                command: npm run build

    deploy:
        docker:
            - image: circleci/node:10-browsers
        steps:
            - run:
                name: Deploy test
                command: echo 'Deploying!!'
            - run:
                name: Building production version
                command: npm run build-prod
            - run:
                name: Firebase Deploy
                command: ./node_modules/.bin/firebase deploy --token "$FIREBASE_TOKEN" --only hosting
workflows:
    version: 2
    build-test-deploy:
        jobs:
            - build-and-test
            - deploy:
                requires: 
                    - build-and-test
                filters:
                    tags:
                        only: /^v[0-9]+.[0-9]+.[0-9]+$/
                    branches:
                        only: master