version: 2.1
jobs:
    build-and-test:
        docker:
            - image: circleci/node:14-browsers
        steps:
            - checkout
            - run:
                name: Show current branch
                command: echo ${CIRCLE_BRANCH}
            - run:
                name: Versions
                command: |
                    echo "Node version: $(node --version)"
                    echo "NPM version: $(yarn --version)"
            - restore_cache:
                keys:
                    - v1-dependencies-{{ checksum "yarn.lock" }}
                    - v1-dependencies-
            - run:
                name: Install local dependencies
                command: yarn install
            - save_cache:
                key: v1-dependencies-{{ checksum "yarn.lock" }}
                paths:
                    - node_modules
            - run:
                name: Linting
                command: yarn run lint
            - run:
                name: Unit test
                command: yarn run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
            # - run:
            #     name: End to End Test
            #     command: yarn run e2e -- --protractor-config=e2e/protractor-ci.conf.js

            - run:
                name: Production build
                command: yarn run build-prod
            - save_cache:
                key: v1-dependencies-{{ checksum "yarn.lock" }}
                paths:
                    - dist
                    - package.json
                    - firebase.json
                    - .firebaserc

    deploy:
        docker:
            - image: circleci/node:14-browsers
        steps:
            - checkout
            - run:
                name: Deploy test
                command: echo 'Deploying to Firebase!!'
            - restore_cache:
                keys:
                    - v1-dependencies-{{ checksum "yarn.lock" }}
                    - v1-dependencies-
            - run:
                name: Building production version
                command: yarn run build-prod
            - run:
                name: Firebase Deploy
                command: ./node_modules/.bin/firebase deploy --token "$FIREBASE_TOKEN" --only hosting
workflows:
    version: 2
    build-and-test:
        jobs:
            - build-and-test:
                filters:
                    tags:
                        ignore: /^v[0-9]+.[0-9]+.[0-9]+$/
    build-test-deploy:
        jobs:
            - build-and-test:
                filters:
                    tags:
                        only: /^v[0-9]+.[0-9]+.[0-9]+$/
                    branches:
                        ignore: /.*/
            - deploy:
                requires: 
                    - build-and-test
                filters:
                    tags:
                        only: /^v[0-9]+.[0-9]+.[0-9]+$/
                    branches:
                        ignore: /.*/
